export enum ConversationActions {
  ADD_MESSAGE = 'conversation/ADD_MESSAGE',
  ADD_CONVERSATION_DATA_MESSAGE = 'conversation/ADD_CONVERSATION_DATA_MESSAGE',
  ADD_CONVERSATION_LIST_MESSAGE = 'conversation/ADD_CONVERSATION_LIST_MESSAGE',
  SEND_MESSAGE = 'conversation/SEND_MESSAGE',
  GET_CONVERSATION_DATA = 'conversation/GET_CONVERSATION_DATA',
  GET_CONVERSATION_LIST = 'conversation/GET_CONVERSATION_LIST',
  SET_CONVERSATION_DATA = 'conversation/SET_CONVERSATION_DATA',
  SET_CONVERSATION_LIST = 'conversation/SET_CONVERSATION_LIST',
  SET_CONVERSATION_ERROR = 'conversation/SET_CONVERSATION_ERROR',
}
