export enum ConversationActions {
  ADD_MESSAGE = 'conversation/ADD_MESSAGE',
  GET_CONVERSATION_LIST = 'conversation/GET_CONVERSATION_LIST',
  SET_CONVERSATION_LIST = 'conversation/SET_CONVERSATION_LIST',
  SET_CONVERSATION_ERROR = 'conversation/SET_CONVERSATION_ERROR',
}
